//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkurseClient.TeacherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", ConfigurationName="TeacherService.TeacherService")]
    public interface TeacherService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message getRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/TeacherService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.TeacherService.getResponse get(VkurseClient.TeacherService.getRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message removeRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/TeacherService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.TeacherService.removeResponse remove(VkurseClient.TeacherService.removeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message insertRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/TeacherService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.TeacherService.insertResponse insert(VkurseClient.TeacherService.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message updateRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/TeacherService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.TeacherService.updateResponse update(VkurseClient.TeacherService.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message getAllRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/TeacherService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.TeacherService.getAllResponse getAll(VkurseClient.TeacherService.getAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public getRequest() {
        }
        
        public getRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getReturn;
        
        public getResponse() {
        }
        
        public getResponse(string getReturn) {
            this.getReturn = getReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class removeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public removeRequest() {
        }
        
        public removeRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", IsWrapped=true)]
    public partial class removeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool removeReturn;
        
        public removeResponse() {
        }
        
        public removeResponse(bool removeReturn) {
            this.removeReturn = removeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string teacher;
        
        public insertRequest() {
        }
        
        public insertRequest(string teacher) {
            this.teacher = teacher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool insertReturn;
        
        public insertResponse() {
        }
        
        public insertResponse(bool insertReturn) {
            this.insertReturn = insertReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string teacher;
        
        public updateRequest() {
        }
        
        public updateRequest(string teacher) {
            this.teacher = teacher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool updateReturn;
        
        public updateResponse() {
        }
        
        public updateResponse(bool updateReturn) {
            this.updateReturn = updateReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/TeacherService.jws", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] getAllReturn;
        
        public getAllResponse() {
        }
        
        public getAllResponse(string[] getAllReturn) {
            this.getAllReturn = getAllReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeacherServiceChannel : VkurseClient.TeacherService.TeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServiceClient : System.ServiceModel.ClientBase<VkurseClient.TeacherService.TeacherService>, VkurseClient.TeacherService.TeacherService {
        
        public TeacherServiceClient() {
        }
        
        public TeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.TeacherService.getResponse VkurseClient.TeacherService.TeacherService.get(VkurseClient.TeacherService.getRequest request) {
            return base.Channel.get(request);
        }
        
        public string get(int ID) {
            VkurseClient.TeacherService.getRequest inValue = new VkurseClient.TeacherService.getRequest();
            inValue.ID = ID;
            VkurseClient.TeacherService.getResponse retVal = ((VkurseClient.TeacherService.TeacherService)(this)).get(inValue);
            return retVal.getReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.TeacherService.removeResponse VkurseClient.TeacherService.TeacherService.remove(VkurseClient.TeacherService.removeRequest request) {
            return base.Channel.remove(request);
        }
        
        public bool remove(int ID) {
            VkurseClient.TeacherService.removeRequest inValue = new VkurseClient.TeacherService.removeRequest();
            inValue.ID = ID;
            VkurseClient.TeacherService.removeResponse retVal = ((VkurseClient.TeacherService.TeacherService)(this)).remove(inValue);
            return retVal.removeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.TeacherService.insertResponse VkurseClient.TeacherService.TeacherService.insert(VkurseClient.TeacherService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public bool insert(string teacher) {
            VkurseClient.TeacherService.insertRequest inValue = new VkurseClient.TeacherService.insertRequest();
            inValue.teacher = teacher;
            VkurseClient.TeacherService.insertResponse retVal = ((VkurseClient.TeacherService.TeacherService)(this)).insert(inValue);
            return retVal.insertReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.TeacherService.updateResponse VkurseClient.TeacherService.TeacherService.update(VkurseClient.TeacherService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(string teacher) {
            VkurseClient.TeacherService.updateRequest inValue = new VkurseClient.TeacherService.updateRequest();
            inValue.teacher = teacher;
            VkurseClient.TeacherService.updateResponse retVal = ((VkurseClient.TeacherService.TeacherService)(this)).update(inValue);
            return retVal.updateReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.TeacherService.getAllResponse VkurseClient.TeacherService.TeacherService.getAll(VkurseClient.TeacherService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public string[] getAll() {
            VkurseClient.TeacherService.getAllRequest inValue = new VkurseClient.TeacherService.getAllRequest();
            VkurseClient.TeacherService.getAllResponse retVal = ((VkurseClient.TeacherService.TeacherService)(this)).getAll(inValue);
            return retVal.getAllReturn;
        }
    }
}
