//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkurseClient.LectureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", ConfigurationName="LectureService.LectureService")]
    public interface LectureService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message getRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.getResponse get(VkurseClient.LectureService.getRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message removeRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.removeResponse remove(VkurseClient.LectureService.removeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message insertRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.insertResponse insert(VkurseClient.LectureService.insertRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message updateRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.updateResponse update(VkurseClient.LectureService.updateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message getAllRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.getAllResponse getAll(VkurseClient.LectureService.getAllRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message findFreeIDRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.findFreeIDResponse findFreeID(VkurseClient.LectureService.findFreeIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://DefaultNamespace) of message insertWithNewIDRequest does not match the default value (http://nebula.innolab.net.ru:8180/axis/LectureService.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        VkurseClient.LectureService.insertWithNewIDResponse insertWithNewID(VkurseClient.LectureService.insertWithNewIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public getRequest() {
        }
        
        public getRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getReturn;
        
        public getResponse() {
        }
        
        public getResponse(string getReturn) {
            this.getReturn = getReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class removeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public removeRequest() {
        }
        
        public removeRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class removeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool removeReturn;
        
        public removeResponse() {
        }
        
        public removeResponse(bool removeReturn) {
            this.removeReturn = removeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insert", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string lecture;
        
        public insertRequest() {
        }
        
        public insertRequest(string lecture) {
            this.lecture = lecture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class insertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool insertReturn;
        
        public insertResponse() {
        }
        
        public insertResponse(bool insertReturn) {
            this.insertReturn = insertReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string lecture;
        
        public updateRequest() {
        }
        
        public updateRequest(string lecture) {
            this.lecture = lecture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool updateReturn;
        
        public updateResponse() {
        }
        
        public updateResponse(bool updateReturn) {
            this.updateReturn = updateReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getAllRequest {
        
        public getAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] getAllReturn;
        
        public getAllResponse() {
        }
        
        public getAllResponse(string[] getAllReturn) {
            this.getAllReturn = getAllReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFreeID", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class findFreeIDRequest {
        
        public findFreeIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFreeIDResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class findFreeIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int findFreeIDReturn;
        
        public findFreeIDResponse() {
        }
        
        public findFreeIDResponse(int findFreeIDReturn) {
            this.findFreeIDReturn = findFreeIDReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertWithNewID", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class insertWithNewIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string lecture;
        
        public insertWithNewIDRequest() {
        }
        
        public insertWithNewIDRequest(string lecture) {
            this.lecture = lecture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertWithNewIDResponse", WrapperNamespace="http://nebula.innolab.net.ru:8180/axis/LectureService.jws", IsWrapped=true)]
    public partial class insertWithNewIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool insertWithNewIDReturn;
        
        public insertWithNewIDResponse() {
        }
        
        public insertWithNewIDResponse(bool insertWithNewIDReturn) {
            this.insertWithNewIDReturn = insertWithNewIDReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LectureServiceChannel : VkurseClient.LectureService.LectureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LectureServiceClient : System.ServiceModel.ClientBase<VkurseClient.LectureService.LectureService>, VkurseClient.LectureService.LectureService {
        
        public LectureServiceClient() {
        }
        
        public LectureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LectureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.getResponse VkurseClient.LectureService.LectureService.get(VkurseClient.LectureService.getRequest request) {
            return base.Channel.get(request);
        }
        
        public string get(int ID) {
            VkurseClient.LectureService.getRequest inValue = new VkurseClient.LectureService.getRequest();
            inValue.ID = ID;
            VkurseClient.LectureService.getResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).get(inValue);
            return retVal.getReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.removeResponse VkurseClient.LectureService.LectureService.remove(VkurseClient.LectureService.removeRequest request) {
            return base.Channel.remove(request);
        }
        
        public bool remove(int ID) {
            VkurseClient.LectureService.removeRequest inValue = new VkurseClient.LectureService.removeRequest();
            inValue.ID = ID;
            VkurseClient.LectureService.removeResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).remove(inValue);
            return retVal.removeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.insertResponse VkurseClient.LectureService.LectureService.insert(VkurseClient.LectureService.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public bool insert(string lecture) {
            VkurseClient.LectureService.insertRequest inValue = new VkurseClient.LectureService.insertRequest();
            inValue.lecture = lecture;
            VkurseClient.LectureService.insertResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).insert(inValue);
            return retVal.insertReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.updateResponse VkurseClient.LectureService.LectureService.update(VkurseClient.LectureService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(string lecture) {
            VkurseClient.LectureService.updateRequest inValue = new VkurseClient.LectureService.updateRequest();
            inValue.lecture = lecture;
            VkurseClient.LectureService.updateResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).update(inValue);
            return retVal.updateReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.getAllResponse VkurseClient.LectureService.LectureService.getAll(VkurseClient.LectureService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public string[] getAll() {
            VkurseClient.LectureService.getAllRequest inValue = new VkurseClient.LectureService.getAllRequest();
            VkurseClient.LectureService.getAllResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).getAll(inValue);
            return retVal.getAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.findFreeIDResponse VkurseClient.LectureService.LectureService.findFreeID(VkurseClient.LectureService.findFreeIDRequest request) {
            return base.Channel.findFreeID(request);
        }
        
        public int findFreeID() {
            VkurseClient.LectureService.findFreeIDRequest inValue = new VkurseClient.LectureService.findFreeIDRequest();
            VkurseClient.LectureService.findFreeIDResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).findFreeID(inValue);
            return retVal.findFreeIDReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VkurseClient.LectureService.insertWithNewIDResponse VkurseClient.LectureService.LectureService.insertWithNewID(VkurseClient.LectureService.insertWithNewIDRequest request) {
            return base.Channel.insertWithNewID(request);
        }
        
        public bool insertWithNewID(string lecture) {
            VkurseClient.LectureService.insertWithNewIDRequest inValue = new VkurseClient.LectureService.insertWithNewIDRequest();
            inValue.lecture = lecture;
            VkurseClient.LectureService.insertWithNewIDResponse retVal = ((VkurseClient.LectureService.LectureService)(this)).insertWithNewID(inValue);
            return retVal.insertWithNewIDReturn;
        }
    }
}
